module.exports = function() {
    return [
        {
            name: "Martin Feld",
            link: "https://listen.hemisphericviews.com/110",
            album_title: "The Cat Empire",
            album_artist: "The Cat Empire",
            album_cover: "cat_empire.jpg",
        },
        {
            name: "Andrew Canion",
            link: "https://listen.hemisphericviews.com/110",
            album_title: "OK Computer",
            album_artist: "Radiohead",
            album_cover: "okcomputer.png",
        },
        {
            name: "Andrew Canion",
            link: "https://listen.hemisphericviews.com/110",
            album_title: "The Dark Side of the Moon",
            album_artist: "Pink Floyd",
            album_cover: "darkside.png",
        },
        {
            name: "Andrew Canion",
            link: "https://listen.hemisphericviews.com/110",
            album_title: "Currents",
            album_artist: "Tame Impala",
            album_cover: "currents.png",
        },
        {
            name: "Jason Burk",
            link: "https://listen.hemisphericviews.com/110",
            album_title: "Random Access Memories",
            album_artist: "Daft Punk",
            album_cover: "random_access_memories.png",
        },
        {
            name: "Flamed Fury",
            link: "https://flamedfury.com/posts/everything-is-recorded-friday-forever/",
            album_title: "Everything is Recorded",
            album_artist: "Friday Forever",
            album_cover: "everything-is-recorded.jpg",
        },
        {
            name: 'Leon Mika',
            link: 'https://lmika.org/2024/05/04/the-perfect-album.html',
            album_artist: 'Jeff Wayne',
            album_title: 'War of the Worlds',
            album_cover: 'wotw.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Chumbawamba',
            album_title: 'English Rebel Songs 1381-1984',
            album_cover: 'englishrebel.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Laura Marling',
            album_title: 'Alas I Cannot Swim',
            album_cover: 'alasicannotswim.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Jillette Johnson',
            album_title: 'Water in a Whale',
            album_cover: 'waterinawhale.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Malcolm Middleton',
            album_title: '5:14 Fluoxytine Seagull Alcohol John Nicotine',
            album_cover: 'fluoxytine.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Nirvana',
            album_title: 'Bleach',
            album_cover: 'bleach.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Alice in Chains',
            album_title: 'Dirt',
            album_cover: 'dirt.jpg',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Nine Inch Nails',
            album_title: 'Broken',
            album_cover: 'broken.png',
        },
        {
            name: 'Thomas Rigby',
            link: 'https://thomasrigby.com/posts/the-perfect-album/',
            album_artist: 'Deftones',
            album_title: 'White Pony',
            album_cover: 'whitepony.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Linkin Park',
            album_title: 'Meteora',
            album_cover: 'meteora.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Sugarcult',
            album_title: 'Palm Trees and Power Lines',
            album_cover: 'palm-tree-and-powerlines.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'My Chemical Romance',
            album_title: 'The Black Parade',
            album_cover: 'theblackparade.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Girl Talk',
            album_title: 'All Day',
            album_cover: 'allday.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Linkin Park',
            album_title: 'Hybrid Theory',
            album_cover: 'hybridtheory.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Bowling for Soup',
            album_title: 'Acoustic in a Freakin Church',
            album_cover: 'acousticinachurch.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Panic! At The Disco',
            album_title: 'A Fever You Cant Sweat Out',
            album_cover: 'afeveryoucantsweatout.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Sum 41',
            album_title: 'All Killer No Filler',
            album_cover: 'allkillernofiller.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Dr Dre',
            album_title: '2001',
            album_cover: '2001.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'Jimmy Eat World',
            album_title: 'Bleed American',
            album_cover: 'bleedamerican.jpg',
        },
        {
            name: 'Robb Knight',
            link: 'https://rknight.me/blog/the-perfect-album/',
            album_artist: 'MC Lars and K.Flay',
            album_title: 'Single and Famous',
            album_cover: 'singleandfamous.jpg',
        },
        {
            name: 'Johnny Noble',
            link: 'https://johnnydecimal.com/20-29-communication/22-blog/22.00.0037-perfect-albums/',
            album_artist: 'Dire Straits',
            album_title: 'Brothers in Arms',
            album_cover: 'brothersinarms.png',
        },
        {
            name: 'Johnny Noble',
            link: 'https://johnnydecimal.com/20-29-communication/22-blog/22.00.0037-perfect-albums/',
            album_artist: 'Destroyer',
            album_title: 'Kaputt',
            album_cover: 'kaputt.png',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Nas',
            album_title: 'Illmatic',
            album_cover: 'illmatic.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Run the Jewels',
            album_title: 'Run the Jewels',
            album_cover: 'runthejewels.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Common',
            album_title: 'Be',
            album_cover: 'be-common.png',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'D\'Angelo',
            album_title: 'Voodoo',
            album_cover: 'voodoo.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Erykah Badu',
            album_title: 'Mama\'s Gun',
            album_cover: 'mamasgun.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Death Cab for Cutie',
            album_title: 'Transatlanticism',
            album_cover: 'transatlanticism.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Nothing',
            album_title: 'Guilty of Everything',
            album_cover: 'guityofeverything.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Robert Glasper',
            album_title: 'In My Element',
            album_cover: 'inmyelement.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'John Coltrane',
            album_title: 'A Love Supreme',
            album_cover: 'alovesupreme.jpg',
        },
        {
            name: 'skoo.bz',
            link: 'https://skoo.bz/2024/05/06/perfect-albums.html',
            album_artist: 'Pearl Jam',
            album_title: 'Ten',
            album_cover: 'ten.jpg',
        },
        {
            name: 'Lou Plummer',
            link: 'https://louplummer.lol/post/the-perfect-album',
            album_artist: 'Bruce Springsteen',
            album_title: 'Nebraska',
            album_cover: 'nebraska.jpg',
        }
    ]
  }